project:
  type: website
  render:
    - "*.qmd"
    - "setup/*.qmd"
    - "analysis/*.qmd"
  output-dir: docs

website:
  title: "Python Setup Tutorial"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Setup
        menu:
          - href: setup/00_setup_slides.qmd
            text: Setup Slides
          - href: setup/01_python_setup.qmd
            text: "Tutorial 1: Python Installation"
          - href: setup/02_create_project_from_scratch.qmd
            text: "Tutorial 2: Create Project"
          - href: setup/03_import_project.qmd
            text: "Tutorial 3: Import Project"
      # - text: Analysis
      #   menu:
      #     - href: analysis/data-cleaning.qmd
      #       text: Data Cleaning
      #     - href: analysis/visualization.qmd
      #       text: Visualization

format:
  html:
    theme: cosmo
    toc: true